image: golang:1.12

variables:
  BIN_NAME: ts2-sim-server
  ARTIFACTS_DIR: pages
  GO_PROJECT: github.com/ts2/ts2-sim-server



pages:

  before_script:
    - apt-get update -qq
    - apt-get install -y -qq doxygen 

  script:
    - go mod download
    - go get github.com/GeertJohan/go.rice/rice
    - ./build_executables.sh
    - doxygen ./docx/doxygen.conf
    - mv build/downloads/ public/
  
  artifacts:
    paths:
    - public
  only:
  - pedro-html
