language: go
go:
 - 1.3.3
 - 1.4.2
 - 1.5.1
 - release
 - tip
install:
  - go get github.com/jteeuwen/go-bindata/...
  - go get github.com/gorilla/websocket
script:
 - go-bindata -debug -pkg server -o server/bindata_templates.go templates/
 - go test -v ./...

