language: go
go:
 - 1.4.2
 - 1.5.1
 - release
 - tip
install:
 - go get github.com/gorilla/websocket
 - go get gopkg.in/inconshreveable/log15.v2
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e50a2fc3d589ff3303f6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
